### PR TITLE
Creating License file

### PR DESCRIPTION
**Pull request by dwcaraway**
Adding an  LGPL v2.1 license file per the license declared at https://opticks.org/display/opticksSDK/Welcome+To+Extension+Development

### CODE REVIEW

**Comment by tclarke** [comment]
This is a read-only mirror of the official repository stored on sourceforge. For change requests, please send an email to the project mailing list.

**Comment by dwcaraway** [comment]
Thanks for the response. It looks like years since any work on the project, is it dead? :skull:

**Comment by tclarke** [comment]
The main funding lines that were paying for most of the work have gone away so development has been limited by this. I've actually been planning on trying to get some of the outstanding issues worked through and a patch release made in the next couple of months. A new feature release will be dependent on interest.
Currently this is a mirror but given that work has nearly stopped I plan on possibly changing this as part of the next release. I need to check with the community and with my management here to make sure everyone is ok if I move the official source and bug tracking to github. If you're interested, subscribe to the dev mailing list (hosted on sourceforge) as that's currently the official communication channel.

**Comment by dwcaraway** [comment]
:ok_hand:  Sounds like a plan. Signed up to the mailing list. I may be doing some work with opticks in the future, if so, happy to pull request any changes back into the master. Hope you're able to officially make github the repo, think the project would get more activity.

**Pull request closed without merging**
